apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prom-v1
spec: 
  destination:
    namespace: dev-monitoring
    server: https://kubernetes.default.svc
  project: prom-v1
  source:
    path: helm/charts/
    repoURL: https://github.com/loydpadgett/kube-prom-stack
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
